# Generated by Django 6.1.1 on 2026-09-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='A Home Built on Compassion', max_length=255)),
                ('subheading', models.CharField(default='More Than a Home — A Sacred Sanctuary to Grow', max_length=255)),
                ('content', models.TextField()),
                ('image', models.CharField(default='/images/photos/campus_main_gate.jpg', max_length=255)),
                ('quote', models.CharField(default='Every child is treated with dignity, care and equal opportunity.', max_length=255)),
                ('cta_text', models.CharField(default='Learn About Bal Sadan', max_length=100)),
                ('cta_url', models.CharField(default='/about', max_length=255)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Clock', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Routine',
                'verbose_name_plural': 'Daily Routines',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DonationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(default='SRIMAD DAYANAND BAL SADAN', max_length=255)),
                ('bank_name', models.CharField(default='Bank of India', max_length=255)),
                ('branch', models.CharField(default='Aishbagh branch, Lucknow', max_length=255)),
                ('account_number', models.CharField(default='680310100008184', max_length=100)),
                ('ifsc', models.CharField(default='BKID0006803', max_length=50)),
                ('upi_id', models.CharField(default='9452158755@okbizicici', max_length=100)),
                ('phone', models.CharField(default='+91 9452158755', max_length=50)),
                ('qr_code', models.CharField(default='/images/photos/donation_upi_qr.jpg', max_length=255)),
                ('instructions', models.TextField(default="Donations can be made by cheque, bank draft, or cash in the name of 'SRIMAD DAYANAND BAL SADAN' or directly via NEFT/RTGS/IMPS/UPI into our official Bank of India account.")),
                ('in_kind_items', models.TextField(default='Ration, fresh fruits, clothing, medicines, educational notebooks & stationery, sports equipment, shoes, slippers, daily toiletries like bath soap, toothpaste, toothbrush, etc.')),
                ('tax_exemption_note', models.CharField(default='Donations eligible for tax exemption under section 80G of the Income Tax Act.', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Donation Information',
                'verbose_name_plural': 'Donation Information',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date', models.DateField()),
                ('time_str', models.CharField(default='10:00 AM - 1:00 PM', max_length=100)),
                ('location', models.CharField(default='Shri Dharm Dutt Sabhagar, Bal Sadan Campus, Lucknow', max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('education', 'Education Infrastructure'), ('residential', 'Residential & Dining'), ('wellness', 'Wellness & Dispensary'), ('culture', 'Culture & Yagyashala'), ('sports', 'Sports & Physical Fitness'), ('sustainability', 'Sustainability & Solar')], default='education', max_length=50)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet points')),
                ('image', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('cover_image', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'History Event',
                'verbose_name_plural': 'History Events',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='SHRIMAD DAYANAND BAL SADAN • LUCKNOW', max_length=255)),
                ('heading', models.CharField(default='Giving Children a Home, Education & Hope.', max_length=255)),
                ('subheading', models.TextField(default='Providing comprehensive care, shelter, formal education, Vedic values, and skill training to orphaned and underprivileged children since 1915.')),
                ('hero_image', models.CharField(default='/images/photos/campus_school_building.jpg', max_length=255)),
                ('primary_cta_text', models.CharField(default='Donate Now', max_length=100)),
                ('primary_cta_url', models.CharField(default='/support-us', max_length=255)),
                ('secondary_cta_text', models.CharField(default='Discover Our Story', max_length=100)),
                ('secondary_cta_url', models.CharField(default='/our-story', max_length=255)),
                ('footer_note', models.CharField(default='Serving children with dignity and Vedic values since 1915', max_length=255)),
            ],
            options={
                'verbose_name': 'Home Hero',
                'verbose_name_plural': 'Home Hero',
            },
        ),
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='Heart', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impact Statistic',
                'verbose_name_plural': 'Impact Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('education', 'Academic Education'), ('skill', 'Vocational Skill'), ('vedic', 'Vedic & Sanskar'), ('wellness', 'Health & Wellness'), ('sports', 'Sports & Martial Arts')], default='skill', max_length=50)),
                ('icon', models.CharField(default='BookOpen', max_length=50)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Program & Skill',
                'verbose_name_plural': 'Programs & Skills',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.CharField(default='/images/photos/campus_school_building.jpg', max_length=255)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Shrimad Dayanand Bal Sadan', max_length=255)),
                ('short_name', models.CharField(default='Bal Sadan', max_length=100)),
                ('tagline', models.CharField(default='Giving Children a Home, Education & Hope', max_length=255)),
                ('logo', models.CharField(default='/images/photos/dayanand_saraswati.jpg', max_length=255)),
                ('favicon', models.CharField(default='/favicon.ico', max_length=255)),
                ('address', models.TextField(default='Moti Nagar, (Near DAV College), Aishbagh Road, Lucknow - 226004, Uttar Pradesh, India')),
                ('primary_phone', models.CharField(default='+91 9452158755', max_length=50)),
                ('secondary_phone', models.CharField(default='+91 9305882580', max_length=50)),
                ('additional_phone', models.CharField(default='+91 9005059992', max_length=50)),
                ('email', models.EmailField(default='dbslucknow@gmail.com', max_length=254)),
                ('website_url', models.URLField(default='https://srimaddayanandbalsadan.in')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('map_url', models.URLField(blank=True, default='https://maps.google.com/?q=Moti+Nagar+DAV+College+Lucknow', max_length=500)),
                ('footer_description', models.TextField(default='A premier charitable residential and educational institution established in 1915, dedicated to the holistic development, care, education, and moral upbringing of orphaned, destitute, and underprivileged children based on Vedic values.')),
                ('donation_cta_text', models.CharField(default='Help Us Build Brighter Futures', max_length=255)),
                ('donation_cta_url', models.CharField(default='/support-us', max_length=255)),
                ('founded_year', models.IntegerField(default=1915)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(default='2026', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.CharField(default='/images/brochure/brochure_page_1.jpg', max_length=255)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sadan.documentcategory')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('campus', 'Campus & Facilities'), ('education', 'Education & Learning'), ('vedic', 'Vedic Chants & Havan'), ('sports', 'Sports & Martial Arts'), ('skills', 'Skill Development'), ('events', 'Events & Celebrations'), ('brochure', 'Original Brochure Pages')], default='campus', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='sadan.galleryalbum')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
