# Generated by Django 6.1.1 on 2026-09-18 10:50

import django.core.validators
import sadan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='uploaded_image',
            field=models.ImageField(blank=True, help_text='Upload an image file directly from your computer (JPG, JPEG, PNG, WEBP up to 10 MB). Takes priority over image URL/path if provided.', null=True, upload_to='gallery/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), sadan.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.CharField(blank=True, help_text='Existing static image path (e.g. /images/photos/campus_school_building.jpg) or external image URL (https://...). Used if no file is uploaded.', max_length=1000),
        ),
    ]
